#!/usr/bin/env python

import numpy as np

"""
Provide input data be passed to the tests in test_reader_region.py.

This is a dictionnary, where keys are filenames, and values are :
    [ (iz,iy,ix), (nz,ny,nx), ]

(iz,iy,ix) locates the first pixel of the region.
(nz,ny,nx) give the length of the region in each dimension.

Expected values are not provided, because they are generated by the INRimage
reader reading the whole image.
"""

data = {

# Codages virgules fixes
# ----------------------

# Codages scalaires

    "a-1o.inr" :  ["a-1o.inr", (6,7), (3,4),],
    "a-1o-s.inr-3d" : ["a-1o-s.inr", (0,6,7), (1,3,4),],
    "a-2o.inr" : ["a-2o.inr", (6,7), (3,4),],
    "a-2o-sun.inr" : ["a-2o-sun.inr" , (6,7), (3,4),],

# Codages vectoriels

    "a-1o-2v.inr" : ["a-1o-2v.inr", (6,7), (3,4),],
    "a-1o-3v.inr" : ["a-1o-3v.inr", (6,7), (3,4),],
    "a-1o-4v.inr" : ["a-1o-4v.inr", (6,7), (3,4),],
    "a-1o-indexed.inr": ["a-1o-indexed.inr", (6,7), (3,4),],
    "a-1o-256x256.inr" : ["a-1o-256x256.inr", (6,7), (3,4),],

# Codages multiplans

    "a-1o-3z.inr" :["a-1o-3z.inr", (0,5,7), (2,3,4) ],
    "a-1o-nz.inr" : ["a-1o-nz.inr", (5,6,7), (2,3,4)],
    "a-1o-3v-nz.inr" : ["a-1o-3v-nz.inr", (5,6,7), (2,3,4),],

# Codage virgule flottante
# ------------------------

    "a-4o-r.inr" : ["a-4o-r.inr", (6,7), (3,4),],
    "a-4o-r-3z.inr" : ["a-4o-r-3z.inr", (0,5,7), (2,3,4)],
    #"a-8o-r-3v.inr" : ["a-8o-r-3v.inr", (0,5,7), (2,3,4)],
    "a-4o-r-2v.vel" : ["a-4o-r-2v.vel", (5,6,7), (2,3,4),],
    #"a-8o-r-3v.inr" : ["a-8o-r-3v.inr", (0,5,7), (2,3,4)],

# Codage par bits packee (virgule fixe)
# -------------------------------------

    "bits/a-p4-indexed.inr" : ["bits/a-p4-indexed.inr", (6,7), (3,4),],
    "bits/a-b1.inr" : ["bits/a-b1.inr", (6,7), (3,4),],

}

print "test_input/reader_region.py:WARNING: Tests on a-8o-r-3v.inr and a-8o-r-3v.inr would failed with message:"
print "test_input/reader_region.py:WARNING: *** glibc detected *** python: free(): corrupted unsorted chunks: 0x0000000002116c80 ***"
print "test_input/reader_region.py:WARNING: These tests are currently skipped."
